### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by multiwebinc** [bennothommo/october-plugin-url-normaliser#1]
I tried to install this plugin and I get the error:

> Update failed
"Unable to parse at line 6 (near "1.0.2")." on line 411 of /path/to/install/vendor/symfony/yaml/Parser.php

**Comment by multiwebinc** [comment]
Nevermind. This happens for installing every plugin for some reason. Something must have broke during an update.

**Comment by bennothommo** [comment]
@multiwebinc If you can narrow down the cause to something inside October CMS or one of the vendor libraries it uses, feel free to submit an issue here: https://github.com/octobercms/october/issues/new/choose.

**Comment by multiwebinc** [comment]
@bennothommo It was actually one of my own plugins. I missed a `:` and it was creating a syntax error. Since it was showing during install of your plugin I assumed that was the culprit.

**Comment by bennothommo** [comment]
Haha, understandable.

**Comment by bennothommo** [comment]
@multiwebinc Just a thought, could you make an issue for that particular case on the October repo? I actually put a patch in for October recently to prevent plugins from being loaded if they have a syntax error. See here: https://github.com/octobercms/october/pull/3956

Your issue may be a particular case that is not covered by this fix.

**Comment by multiwebinc** [comment]
@bennothommo Good idea. Done!
