### ISSUE TITLE
Error - Undefined index: path

### ISSUE THREAD

**Issue by iboved** [bennothommo/october-plugin-url-normaliser#4]
Hi!
I have the following error: `Undefined index: path`

UrlNormaliser version 1.1.1
OctoberCMS build 458

![image](https://user-images.githubusercontent.com/9253603/72796660-63544380-3c48-11ea-9c0c-b1453718a368.png)

There is situation when `parse_url ` function does not have a `path` component. For example, when we parse such a URL: `parse_url('http://site.com');` this function return the following result:
```
array (
  'scheme' => 'http',
  'host' => 'site.com',
)
```

**Comment by bennothommo** [comment]
@iboved Thanks for the report, and apologies for the delay. I'll take a look at this now and will push out a fix shortly.

**Comment by bennothommo** [comment]
@iboved This is now fixed by the v1.1.2 update.
