### ISSUE TITLE
Error: parse_url() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by iboved** [bennothommo/october-plugin-url-normaliser#6]
Take a look at [getHostname](https://github.com/bennothommo/october-plugin-url-normaliser/blob/master/classes/Normalise.php#L219) method.
If we don't have `$_SERVER['SERVER_NAME']` variable, the plugin tries to get url from [url()](https://github.com/bennothommo/october-plugin-url-normaliser/blob/master/classes/Normalise.php#L222) function. But `url()` function returns `\October\Rain\Router\UrlGenerator` instance instead of current url. Therefore we have the error:

> parse_url() expects parameter 1 to be string, object given

I think you should use `url()->current()` instead of `url()`.

**Comment by bennothommo** [comment]
Thanks for the report @iboved - I'll push out a fix for this shortly! :)

**Comment by bennothommo** [comment]
@iboved Extremely sorry for the delay. This fix will be out shortly with the 1.1.7 update.
