### ISSUE TITLE
Applying normalization to Static Menu breaks with type "Header"

### ISSUE THREAD

**Issue by jeremymouton** [bennothommo/october-plugin-url-normaliser#9]
Applying normalization to Static Menu breaks with type "Header".

## Expected Behavior
The "Header" menu should be rendered, without normalization since it does not have a link.

## Actual Behavior

Breaks frontend and returns error:

```
Type error: Argument 1 passed to BennoThommo\UrlNormaliser\Classes\Normalise::url() must be of the type string, null given, called in /var/www/html/plugins/bennothommo/urlnormaliser/Plugin.php on line 92
```

## Steps to reproduce

- Install BennoThommo.Meta and BennoThommo.UrlNormaliser
- Enable "Normalise URLs in navigation menus?" option in Url Normaliser settings
- Create or update existing Static Menu with a menu item using the type "Header"
- Save menu
- Reload frontend

**Comment by bennothommo** [comment]
Thanks for letting me know @jeremymouton - I'll try and take a look soon.
